"""Backend diagnostic state == what the frontend renders.

`frontend/src/test/fixtures/pipeline_no_signal.json` is generated by the REAL backend
(real V8DStrategy, a real NIFTY50 window, the real scanner and `build_pipeline`).
This test fails if the backend output drifts from the committed fixture; the
Vitest suite renders the same fixture and asserts every displayed value. Regenerate
with:  UPDATE_PIPELINE_FIXTURE=1 pytest backend/tests/test_pipeline_frontend_contract.py
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

from backend.paper import scan_state as ss
from backend.tests.test_scanner_runtime_pipeline import worker  # noqa: F401
from backend.tests.test_v8d_signal_to_execution import _engine, _find, _now_after_close, _scanner
from backend.tests.test_ai_decision_layer import APPROVE_JSON

ROOT = Path(__file__).resolve().parents[2]
FIXTURE = ROOT / "frontend/src/test/fixtures/pipeline_no_signal.json"
FIXED_NOW = datetime(2026, 10, 1, 5, 0, 0, tzinfo=timezone.utc)


def _backend_pipeline(worker):
    w, _e = _find("NIFTY50", lambda x: x["decision"] is None and x["binding_condition"] == "trend" and x["evaluated"])
    worker.db.save_setting("paper_reconcile_ok", "1")
    sc = _scanner(worker, "NIFTY50", w, _engine(worker, [APPROVE_JSON]))
    res = sc.scan_once(worker.runtime, trades_today=0, kill_switch_active=False)
    rec = ss.build_scan_record(seq=1, scanned=res.scanned, traded=res.traded, reason=res.reason, signal=res.signal,
                               details=res.details, strategy="V8_D_PULLBACK_ATM", underlying="NIFTY50", now=FIXED_NOW)
    pipe = ss.build_pipeline(rec, ss.RUNNING_NO_SIGNAL, symbols=[ss.symbol_summary(rec)])
    return json.loads(json.dumps(pipe, default=str, sort_keys=True))


def test_backend_pipeline_matches_the_committed_frontend_fixture(worker):
    got = _backend_pipeline(worker)
    if os.environ.get("UPDATE_PIPELINE_FIXTURE") == "1":
        FIXTURE.write_text(json.dumps(got, indent=2, sort_keys=True) + "\n")
    assert FIXTURE.exists(), "run with UPDATE_PIPELINE_FIXTURE=1 to create the fixture"
    assert got == json.loads(FIXTURE.read_text()), "backend pipeline drifted from the frontend fixture"


def test_pipeline_has_every_field_the_frontend_type_declares(worker):
    got = _backend_pipeline(worker)
    ts = (ROOT / "frontend/src/types/pipeline.ts").read_text()
    body = ts.split("export interface PipelineView {")[1].split("\n}\n")[0]
    declared = set(re.findall(r"^\s{2}([a-z_0-9]+)\??:", body, flags=re.M))
    assert {"scanner", "market", "strategy", "latest_signal", "ai_decision", "risk_check", "execution", "outcome",
            "final", "v8d", "symbols"} <= declared
    missing = declared - set(got)
    assert not missing, f"frontend declares fields the backend does not send: {missing}"
    assert got["outcome"] == "NO_SIGNAL" and got["final"] == "NO TRADE" and got["execution"] == "NOT ATTEMPTED"
    v = got["v8d"]
    assert v["evaluated"] and v["binding_condition"] == "trend" and v["ce"]["trend"]["pass"] in (True, False)
